#include "UDLODTerrainShaders.h"

#define UDLOD_SHADER_PATH "/Plugins/UDLODTerrain/UDLOD_Terrain.usf"

IMPLEMENT_GLOBAL_SHADER(FUDLOD_RootTileCS, UDLOD_SHADER_PATH, "MainCS_Root", SF_Compute);
IMPLEMENT_GLOBAL_SHADER(FUDLOD_MakeDispatchArgsCS, UDLOD_SHADER_PATH, "MainCS_Dispatch", SF_Compute);
IMPLEMENT_GLOBAL_SHADER(FUDLOD_RefineCS, UDLOD_SHADER_PATH, "MainCS_Refine", SF_Compute);
IMPLEMENT_GLOBAL_SHADER(FUDLOD_DrawArgsCS, UDLOD_SHADER_PATH, "MainCS_DrawArgs", SF_Compute);

IMPLEMENT_GLOBAL_SHADER(FUDLOD_TerrainVS, UDLOD_SHADER_PATH, "MainVS", SF_Vertex);
IMPLEMENT_GLOBAL_SHADER(FUDLOD_TerrainPS, UDLOD_SHADER_PATH, "MainPS", SF_Pixel);

IMPLEMENT_UNIFORM_BUFFER_STRUCT(UDLOD_DispatchCB, "DispatchCB")
IMPLEMENT_UNIFORM_BUFFER_STRUCT(UDLOD_RefineCB, "RefineCB")
IMPLEMENT_UNIFORM_BUFFER_STRUCT(UDLOD_DrawArgsCB, "DrawArgsCB")
IMPLEMENT_UNIFORM_BUFFER_STRUCT(UDLOD_VSParamsCB, "VSParamsCB")
